# Generated by Django 4.1 on 2022-08-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="sex",
            field=models.CharField(
                choices=[("male", "Samiec"), ("female", "Samica")],
                max_length=50,
                verbose_name="Płeć",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="size",
            field=models.CharField(
                choices=[
                    ("small", "Mały zwierzak"),
                    ("medium", "Średni zwierzak"),
                    ("big", "Duzy zwierzak"),
                ],
                max_length=50,
                verbose_name="Rozmiar",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="spice",
            field=models.CharField(
                choices=[("dog", "Pies"), ("cat", "Kot"), ("other", "Inne")],
                max_length=50,
                verbose_name="Gatunek",
            ),
        ),
    ]
