# Generated by Django 4.1 on 2022-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoptions", "0002_alter_animal_sex_alter_animal_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="contacts",
        ),
        migrations.AlterField(
            model_name="animal",
            name="size",
            field=models.CharField(
                choices=[
                    ("small", "Mały zwierzak"),
                    ("medium", "Średni zwierzak"),
                    ("big", "Duży zwierzak"),
                ],
                max_length=50,
                verbose_name="Rozmiar",
            ),
        ),
    ]
