# Generated by Django 4.1 on 2022-08-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adoptions", "0003_remove_animal_contacts_alter_animal_size"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
